"""
discovery.py — the generated discovery settings `protorig run` hands every app.

Two flavours, both a small QoS XML file with one profile, protorig_node::Participant
(based on protorig_base::Base, so the shared liveliness settings still apply).
fw.App loads it through the PROTORIG_NODE_QOS environment variable; C/C++ apps
will load the same file, so every language discovers the same way.

  --sim   this machine only (U3): shared memory is the only transport, so nothing
          reaches the network. A sim run on domain 0 can't mix with a powered-on
          TC397 or the real rig, yet Admin Console on the same PC sees it all.

  --node  one rig machine (U4): unicast discovery with every other node's IP as
          an initial peer, and DDS restricted to this node's own IP. The
          restriction is the lesson from the known-good TC397 host profile:
          a PC with several network cards otherwise advertises addresses the
          ECU can't reach, and data silently never arrives.

Multicast discovery is off in both: the rig uses unicast peers only, so
switch settings (IGMP snooping) can't break discovery.

Also here: which node this machine is (U13, from its IP) and whether this
machine fits the node's os:/arch: (U5). Shared by `run` and, later, `agent`.
"""
from __future__ import annotations

import ipaddress
import platform
import socket
from xml.sax.saxutils import escape

# No "--" anywhere in comments: XML forbids it (so "sim mode", not the option name).
HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by protorig run for {what}. Do not edit: it is rewritten on every run. -->
<dds>
  <qos_library name="protorig_node">
    <qos_profile name="Participant" base_name="protorig_base::Base">
      <domain_participant_qos>
"""
FOOTER = """      </domain_participant_qos>
    </qos_profile>
  </qos_library>
</dds>
"""
MIN_PEER_INDEX = 4      # participants announced to per peer machine (like the known-good profile's "4@")


def sim_qos() -> str:
    """Settings for --sim: shared memory only, so nothing leaves this machine."""
    return HEADER.format(what="sim mode (this machine only)") + """\
        <transport_builtin><mask>SHMEM</mask></transport_builtin>
        <discovery>
          <initial_peers><element>builtin.shmem://</element></initial_peers>
          <multicast_receive_addresses/>
        </discovery>
""" + FOOTER


def peer_index(node_spec: dict) -> int:
    """How many participants to announce to on a peer machine: one per app it
    runs plus spare, at least MIN_PEER_INDEX (Connext's "N@" peer prefix)."""
    run = node_spec.get("run") or []
    return max(MIN_PEER_INDEX, len(run) + 1) if isinstance(run, list) else MIN_PEER_INDEX


def node_qos(nodes: dict, this: str) -> str:
    """Settings for --node <this>: every other node as a unicast peer, DDS bound
    to this node's own IP; shared memory for the apps on this same machine."""
    me = nodes[this]["ip"]
    peers = [f"{peer_index(spec)}@builtin.udpv4://{spec['ip']}"
             for name, spec in nodes.items() if name != this and isinstance(spec, dict) and spec.get("ip")]
    peer_xml = "".join(f"            <element>{escape(p)}</element>\n" for p in peers)
    return HEADER.format(what=f"node {escape(this)}") + f"""\
        <transport_builtin>
          <mask>UDPv4|SHMEM</mask>
          <udpv4>
            <allow_interfaces_list><element>{escape(me)}</element></allow_interfaces_list>
            <max_interface_count>1</max_interface_count>
          </udpv4>
        </transport_builtin>
        <discovery>
          <initial_peers>
            <element>builtin.shmem://</element>
{peer_xml}          </initial_peers>
          <multicast_receive_addresses/>
        </discovery>
""" + FOOTER


def is_local_ip(ip: str) -> bool:
    """True if this machine has this IPv4 address (U5). Binding a socket to an
    address only works when a network card here owns it: portable, no extra packages.
    Only a real, specific IPv4 counts: "" and 0.0.0.0 would bind to "any card", which
    proves nothing."""
    try:
        addr = ipaddress.IPv4Address(str(ip))
    except (ipaddress.AddressValueError, ValueError):
        return False
    if addr.is_unspecified or addr.is_multicast:
        return False
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.bind((ip, 0))
        return True
    except (OSError, ValueError, TypeError, OverflowError):
        return False



# ------------------------------------------------------------------ which node am I? (U13, U5)

# scenario.yaml's words for what Python's platform module reports. Windows says
# AMD64 or ARM64, Linux x86_64 or aarch64, a 32-bit Raspberry Pi OS armv7l.
OS_NAMES = {"linux": "linux", "windows": "windows", "qnx": "qnx", "android": "android"}
ARCH_NAMES = {"x86_64": "x86_64", "amd64": "x86_64", "x64": "x86_64",
              "aarch64": "aarch64", "arm64": "aarch64", "armv7l": "armv7", "armv7": "armv7"}
DEFAULT_ARCH = "x86_64"      # what scenario.yaml means when a node gives no arch: (as in `protorig check`)


class NodeError(Exception):
    """This machine can't be matched to a node; the message says what to do."""


def machine_kind(system: str, machine: str) -> tuple[str, str]:
    """(os, arch) in scenario.yaml's words, from platform.system() and platform.machine().
    Unknown names pass through lowercased, so they simply match no node."""
    s, m = str(system).strip().lower(), str(machine).strip().lower()
    return OS_NAMES.get(s, s), ARCH_NAMES.get(m, m)


def this_machine() -> tuple[str, str]:
    """This machine's (os, arch), e.g. ("windows", "x86_64")."""
    return machine_kind(platform.system(), platform.machine())


def find_node(nodes: dict, is_local=is_local_ip) -> str:
    """U13: the one managed node whose ip: this machine has. External nodes never
    count (nothing runs there). None or several: NodeError, saying what to do."""
    managed = {n: s for n, s in nodes.items() if isinstance(s, dict) and not s.get("external")}
    mine = [n for n, s in managed.items() if is_local(str(s.get("ip", "")))]
    if len(mine) == 1:
        return mine[0]
    if not mine:
        listing = ", ".join(f"{n} {s.get('ip', '(no ip)')}" for n, s in managed.items()) or "none"
        raise NodeError(f"this machine has none of its managed nodes' IPs ({listing}). Run this on one of "
                        "those machines, fix the ip: lines in scenario.yaml (the same file on every "
                        "machine), or use --sim on a single PC.")
    listing = ", ".join(f"{n} {managed[n].get('ip')}" for n in mine)
    raise NodeError(f"this machine has the IPs of several nodes ({listing}). "
                    "Name the one you mean: --node <node>.")


def kind_mismatch(node: str, spec: dict, machine: tuple[str, str] | None = None) -> str:
    """U5: "" if this machine fits the node's os: and arch:, else why not.
    Catches an IP that moved to another machine (e.g. DHCP gave the VM the Pi's
    address), which would otherwise run the wrong node's apps, silently."""
    os_, arch = machine or this_machine()
    problems = []
    want_os = spec.get("os")
    if want_os is not None and str(want_os).strip().lower() != os_:
        problems.append(f"os: {want_os} but this machine is {os_}")
    want_arch = spec.get("arch", DEFAULT_ARCH)
    if str(want_arch).strip().lower() != arch:
        given = "" if "arch" in spec else " (none given, so x86_64 is assumed)"
        problems.append(f"arch: {want_arch}{given} but this machine is {arch}")
    if not problems:
        return ""
    return (f"node '{node}' has {'; '.join(problems)}. Its IP may now belong to another machine "
            "(give the rig fixed IPs), or fix os:/arch: in scenario.yaml.")
