"""
discovery.py — the generated discovery settings `protorig run` hands every app.

Two flavours, both a small QoS XML file with one profile, protorig_node::Participant
(based on protorig_base::Base, so the shared liveliness settings still apply).
fw.App loads it through the PROTORIG_NODE_QOS environment variable; C/C++ apps
will load the same file, so every language discovers the same way.

  --sim   this machine only (U3): shared memory is the only transport, so nothing
          reaches the network. A sim run on domain 0 can't mix with a powered-on
          TC397 or the real rig, yet Admin Console on the same PC sees it all.

  --node  one rig machine (U4): unicast discovery with every other node's IP as
          an initial peer, and DDS restricted to this node's own IP. The
          restriction is the lesson from the known-good TC397 host profile:
          a PC with several network cards otherwise advertises addresses the
          ECU can't reach, and data silently never arrives.

Multicast discovery is off in both: the rig uses unicast peers only, so
switch settings (IGMP snooping) can't break discovery.
"""
from __future__ import annotations

import ipaddress
import socket
from xml.sax.saxutils import escape

# No "--" anywhere in comments: XML forbids it (so "sim mode", not the option name).
HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by protorig run for {what}. Do not edit: it is rewritten on every run. -->
<dds>
  <qos_library name="protorig_node">
    <qos_profile name="Participant" base_name="protorig_base::Base">
      <domain_participant_qos>
"""
FOOTER = """      </domain_participant_qos>
    </qos_profile>
  </qos_library>
</dds>
"""
MIN_PEER_INDEX = 4      # participants announced to per peer machine (like the known-good profile's "4@")


def sim_qos() -> str:
    """Settings for --sim: shared memory only, so nothing leaves this machine."""
    return HEADER.format(what="sim mode (this machine only)") + """\
        <transport_builtin><mask>SHMEM</mask></transport_builtin>
        <discovery>
          <initial_peers><element>builtin.shmem://</element></initial_peers>
          <multicast_receive_addresses/>
        </discovery>
""" + FOOTER


def peer_index(node_spec: dict) -> int:
    """How many participants to announce to on a peer machine: one per app it
    runs plus spare, at least MIN_PEER_INDEX (Connext's "N@" peer prefix)."""
    run = node_spec.get("run") or []
    return max(MIN_PEER_INDEX, len(run) + 1) if isinstance(run, list) else MIN_PEER_INDEX


def node_qos(nodes: dict, this: str) -> str:
    """Settings for --node <this>: every other node as a unicast peer, DDS bound
    to this node's own IP; shared memory for the apps on this same machine."""
    me = nodes[this]["ip"]
    peers = [f"{peer_index(spec)}@builtin.udpv4://{spec['ip']}"
             for name, spec in nodes.items() if name != this and isinstance(spec, dict) and spec.get("ip")]
    peer_xml = "".join(f"            <element>{escape(p)}</element>\n" for p in peers)
    return HEADER.format(what=f"node {escape(this)}") + f"""\
        <transport_builtin>
          <mask>UDPv4|SHMEM</mask>
          <udpv4>
            <allow_interfaces_list><element>{escape(me)}</element></allow_interfaces_list>
            <max_interface_count>1</max_interface_count>
          </udpv4>
        </transport_builtin>
        <discovery>
          <initial_peers>
            <element>builtin.shmem://</element>
{peer_xml}          </initial_peers>
          <multicast_receive_addresses/>
        </discovery>
""" + FOOTER


def is_local_ip(ip: str) -> bool:
    """True if this machine has this IPv4 address (U5). Binding a socket to an
    address only works when a network card here owns it: portable, no extra packages.
    Only a real, specific IPv4 counts: "" and 0.0.0.0 would bind to "any card", which
    proves nothing."""
    try:
        addr = ipaddress.IPv4Address(str(ip))
    except (ipaddress.AddressValueError, ValueError):
        return False
    if addr.is_unspecified or addr.is_multicast:
        return False
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.bind((ip, 0))
        return True
    except (OSError, ValueError, TypeError, OverflowError):
        return False
