"""
lock.py — `protorig lock <external>`: record what an external node was flashed with.

Run it right after flashing, once you've confirmed the board runs the current
IDL. It writes external/<name>/flashed.lock with a SHA-256 fingerprint of each
IDL file the firmware was built from. From then on, `protorig check` warns when
any of those files changes, so the repo and the board can't silently drift.

Files locked:
  - every .idl in interfaces/external/<name>/
  - files locked last time (e.g. common IDL the node also uses)
  - anything passed with --add (e.g. --add interfaces/common/vehicle.idl)
"""
from __future__ import annotations

import datetime as dt
from pathlib import Path

import yaml

import repo
from check_contract import lock_path, sha256

HEADER = """# Generated by `protorig lock {name}` — do not edit by hand.
# Fingerprints of the IDL files the {name} firmware was built from.
# `protorig check` warns when any of them changes: regenerate and reflash
# the node, then run `protorig lock {name}` again.
"""


def files_to_lock(name: str, add: list[str]) -> tuple[list[str], list[str]]:
    """(files, problems) — repo-relative paths to lock, and anything wrong with the request."""
    problems, files = [], set()
    idl_dir = repo.ROOT / "interfaces" / "external" / name
    files.update(str(p.relative_to(repo.ROOT)) for p in idl_dir.glob("*.idl"))
    old = lock_path(name)
    if old.exists():
        try:
            files.update((yaml.safe_load(old.read_text(encoding="utf-8")) or {}).get("files", {}))
        except yaml.YAMLError:
            problems.append(f"{old.relative_to(repo.ROOT)} is unreadable; it will be rewritten")
    for a in add:
        p = (repo.ROOT / a).resolve()
        try:
            r = str(p.relative_to(repo.ROOT))
        except ValueError:
            problems.append(f"{a}: outside the repo")
            continue
        if not p.is_file() or p.suffix != ".idl":
            problems.append(f"{a}: not an .idl file in the repo")
        else:
            files.add(r)
    missing = [f for f in files if not (repo.ROOT / f).exists()]
    for f in missing:
        problems.append(f"{f} was in the old lock but no longer exists; it is dropped")
        files.discard(f)
    return sorted(files), problems


def main(args) -> int:
    name = args.name
    if not (repo.ROOT / "external" / name).is_dir():
        print(f"protorig lock: no external/{name}/ folder. External nodes: "
              + ", ".join(sorted(p.name for p in (repo.ROOT / "external").iterdir() if p.is_dir())))
        return 1
    files, problems = files_to_lock(name, args.add or [])
    hard = [p for p in problems if "outside the repo" in p or "not an .idl" in p]
    for p in problems:
        print(("ERROR " if p in hard else "note  ") + p)
    if hard:
        return 1
    if not files:
        print(f"protorig lock: no IDL files for {name} (expected interfaces/external/{name}/*.idl or --add)")
        return 1
    data = {"locked": dt.date.today().isoformat(),
            "files": {f: sha256(repo.ROOT / f) for f in files}}
    print(f"{'Would lock' if args.dry_run else 'Locking'} {name} to:")
    for f, d in data["files"].items():
        print(f"  {f}  {d[:19]}…")
    if not args.dry_run:
        lock_path(name).write_text(HEADER.format(name=name) + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
        print(f"Wrote {lock_path(name).relative_to(repo.ROOT)}")
    return 0
